### PR TITLE
Remove unnecessary calls to require 'mail'

### PR DESCRIPTION
**Pull request by merhard**
per discussion here: https://github.com/hallelujah/valid_email/pull/58

### CODE REVIEW

**Comment by tmornini** [comment]
@merhard Nice!

**Comment by badosu** [comment]
I use only the `email_validator` file so it was not really unnecessary. Not a big deal though.

**Comment by tmornini** [comment]
@merhard Ping

**Comment by merhard** [comment]
@badosu

The `email_validator` file **does not** use any code from the [mail gem](https://github.com/mikel/mail). Therefore, it **should not** `require 'mail'`.

The `email_validator` file **does** use code from the `validate_email` file. Therefore, it **should** `require 'valid_email/validate_email'`.

The `validate_email` file **does** use code from the [mail gem](https://github.com/mikel/mail). Therefore, it **should** `require 'mail'`.

---
The `require 'mail'` line belongs in the file that actually needs the [mail gem](https://github.com/mikel/mail) to be loaded. This is the `validate_email` file.

The `require 'mail'` line does not belong in files where the [mail gem](https://github.com/mikel/mail) is not used. These are the files addressed in this pull request, including the `email_validator` file.

**Comment by badosu** [comment]
@merhard See https://github.com/tmornini/valid_email/blob/master/lib/valid_email/validate_email.rb#L10

It raises unitinialized constant `Mail` if you don't require mail/

**Comment by merhard** [comment]
@badosu, this pull request is for the `require_mail` branch. You seem to be using the `master` branch of this fork. See https://github.com/hallelujah/valid_email/pull/58/files for all of the changes that branch has from the actual project https://github.com/hallelujah/valid_email.

**Comment by badosu** [comment]
Oh, ok, great!! :-)

**Pull request merged**
